### ISSUE TITLE
Remove user context

### ISSUE THREAD

**Issue by seravifer** [elastic/apm-agent-rum-js#1085]
Is there a way to remove the user from context?
If I set the user, then I can't delete it.

Something like that:
```
setUserContext({ id: '1234' });
captureError('My error with user');
logout();
setUserContext(null);
captureError('My error without user');
```

**Comment by vigneshshanmugam** [comment]
Hi @seravifer, There is a validation in place that checks for undefined values and rejects those updates which is why you are not able to see the updated value. 

There are two possibilities here,

1. Resetting the user context with empty values - Fastest
```
apm.setUserContext({ id: '', email: '' })
// Will reset the provided user data to empty values which will get dropped eventually when sending payload
```

2. Perfoms a deep update of config with previous context config
```
apm.config({ context: { user: {} } }) 
 // Rests all user context data. 
```

Let us know if you need more details.
