### ISSUE TITLE
console errors not getting sent when using apm-agent-rum-js with angular

### ISSUE THREAD

**Issue by suraj-dot-gupta** [elastic/apm-agent-rum-js#1235]
Hi, i have created a custom js library using this `apm-agent-rum-js` , while running the directly in the library errors are getting captured and event is sent.
But same library if i use in angular app, http requests works but the console errors wont  work as it doesnt sends a event.

i dont want to use @elastic/apm-rum-angular package

Thanks !
Any help would be appreciated

**Comment by devcorpio** [comment]
Hi @suraj-dot-gupta,

Thanks for reaching out!

- What is the version of RUM and Angular that you are using?
- Is there any code snippet that you can share?


Let me know if what I'm describing is correct:

You have a website which includes your library and the rum agent. When your library throws an error the agent catches it and sends an event.

But that doesn't happen when you that error happens in an angular app.


Am I describing the scenario properly?

Thanks,
Alberto

**Comment by suraj-dot-gupta** [comment]
Thanks @devcorpio for your response,

No, actually in all javascript frameworks or javascript the agent  catches error and sends an event.
Only when i use in angular , it doesnt catch any error.

 i am using agent version "@elastic/apm-rum": "^5.8.0"
 
 sample code: 
 
 ```
import { init as initApm } from '@elastic/apm-rum';
const apm = initApm({
            // Set required service name (allowed characters: a-z, A-Z, 0-9, -, _, and space)
            serviceName: serviceName,
            // Set custom APM Server URL (default: http://localhost:8200)
            serverUrl: 'server_url,
            // Set service version (required for sourcemap feature)
            serviceVersion: ''
        });
```

Thanks!!

**Comment by devcorpio** [comment]
Hi @suraj-dot-gupta,

What version of angular are you using?

Thanks!

**Comment by vigneshshanmugam** [comment]
By default, when an error is thrown inside the Angular application, the default error handler prints the error messages to the console without rethrowing them as browser events which is why RUM agent will not be able to capture those errors and report it. 

Details here - https://www.elastic.co/guide/en/apm/agent/rum-js/current/angular-integration.html#_capturing_errors_in_angular_applications

> i dont want to use @elastic/apm-rum-angular package

If you dont want to use the Angular package, you need to extend the Angular `ErrorHandler` class and add handle the error and report it to the APM server. See example code here - https://github.com/elastic/apm-agent-rum-js/blob/9bb158c22d0ae1f6ef6ea1679930c79814b60dcf/packages/rum-angular/src/error-handler.ts#L31-L40

**Comment by suraj-dot-gupta** [comment]
Thanks @vigneshshanmugam, working perfectly fine.
