### ISSUE TITLE
CORS Error in APM integration

### ISSUE THREAD

**Issue by fsalazarh** [elastic/apm-agent-rum-js#1251]
Hi!

I'm using `@elastic/apm-rum v5.12.0`

I've spent a lot of time trying to figure out why the CORS integration to send RUM events to elastic doesn't work for me, and I still really don't know what's wrong or missing in the configuration.

The Elastic Cloud Agent Policy is the follow:

![image](https://user-images.githubusercontent.com/8340890/175078097-fd9b0013-6027-4671-a935-5845fec92492.png)

I mean, in theory it is allowing communication with any origin, however I get a cors error and I can't send the events.

![image](https://user-images.githubusercontent.com/8340890/175078477-1685ad22-e6e8-4ade-a1c5-4df8edf994fa.png)

Any help please?

**Comment by kyungeunni** [comment]
Hi @fsalazarh!! 

Could you try to update the Origin Headers to `"*"`, without square brackets (instead of`["*"]`) and see if it helps?

If it doesn't resolve problems for you, could you let me know the APM server version and whether you are running a standalone APM server or only via APM integration?

**Comment by fsalazarh** [comment]
Hi @kyungeunni 
> 
> Could you try to update the Origin Headers to `"*"`, without square brackets (instead of`["*"]`) and see if it helps?
> 
Yes, I'm tried with `"*"` instead of `["*"]` and the behaviour is the same. 

> If it doesn't resolve problems for you, could you let me know the APM server version and whether you are running a standalone APM server or only via APM integration?

APM v8.2.0 via APM Integration. This integration worked for me with previous versions of APM, but since the last versions (with fleet integration) I haven't been able to get it to work. 

![image](https://user-images.githubusercontent.com/8340890/175317540-69a5eb60-3e78-4b8b-9821-ae2333355de5.png)

**Comment by kyungeunni** [comment]
I see - that is odd. Could you able to check your Elastic Agent status? You can check by navigating to _Management > Fleet_ in Kibana. Does it say unhealthy?
There is a case when APM server is not able to apply the saved configuration because it doesn't pass validation(even though it passed frontend validation from the UI)

**Comment by fsalazarh** [comment]
> I see - that is odd. Could you able to check your Elastic Agent status? You can check by navigating to _Management > Fleet_ in Kibana. Does it say unhealthy?

![image](https://user-images.githubusercontent.com/8340890/175616310-edb326bc-3945-4b4b-a802-a4beef0cec25.png)

> There is a case when APM server is not able to apply the saved configuration because it doesn't pass validation(even though it passed frontend validation from the UI)

How can I check that this is not the case? or what other settings can I check?

**Comment by devcorpio** [comment]
Hi @fsalazarh,

Thanks for all those details and the screenshots!

In your Firefox screenshot I noticed something that might be interesting. You are getting a **[502](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502)** status code from the preflight request. The status code should be **200** instead. Additionally, you are receiving response headers (302B) and response (63B), in my case the size of my response is 0B. (neither on Chrome nor Firefox). What do you see in the response tab? Another thing that caught my attention in your screenshot the preflight request content-type is **json**, it should be **text/plain** instead.

Could you check that on Chrome, too? (the status code, the response headers, and the response)

What does happen if you copy the request as CURL and execute it in a terminal?

<img width="611" alt="Screenshot 2022-06-28 at 17 20 44" src="https://user-images.githubusercontent.com/15065076/176217453-3e82f45d-c9be-4dd0-ab00-62b334a851a2.png">

Please, add the flag [--verbose](https://curl.se/docs/manpage.html#-v) in the curl command so you can see all the details.

One other thing that might be great to do in an isolated way, for instance:

```
<!DOCTYPE html>
<html>
    <head>
        <script src="https://unpkg.com/@elastic/apm-rum@5.12.0/dist/bundles/elastic-apm-rum.umd.min.js"></script>
    </head>
    <body>
        Hello, this is a local app with the RUM agent injected
        <script>
            elasticApm.init({
                serviceName: 'your-service-name',
                serverUrl: 'your-server-url',
            })


            elasticApm.observe('transaction:end', (tr) => {
                console.log("tr", tr)
            })
        </script>
    </body>
</html>
```

And see if the CORS error is triggered there too. Honestly, I don't think this is going to modify the behaviour since the problem seems to be on the server.

Other that you might check is:

- What does happen if you try to restart the deployment? Does it work? 
<img width="192" alt="Screenshot 2022-06-28 at 17 43 15" src="https://user-images.githubusercontent.com/15065076/176222569-ccd6e541-f231-41a7-8e70-ffaaa72dc463.png">

- Perhaps, just for the sake of narrowing the problem even more. Would it be possible to create another deployment (only for a quick test) and to see if the error is triggered, too? Bear in mind that you will not need to modify anything, just to copy the endpoint. (since the wildcard is the default value). I understand that this might have a cost, so please, skip this step if inconvenient.


Cheers,
Alberto

**Comment by fsalazarh** [comment]
Hi @devcorpio 

> What do you see in the response tab? Another thing that caught my attention in your screenshot is that the preflight request content-type is **json**, it should be **text/plain** instead.

### OPTIONS Headers in Firefox

![image](https://user-images.githubusercontent.com/8340890/176288612-624661bb-3fea-4b04-997a-86b53e277e5e.png)

### POST Headers in Firefox 

![image](https://user-images.githubusercontent.com/8340890/176288814-751f0485-11fa-4bb8-b9f9-4a2f492ffe8c.png)

### OPTIONS response in Firefox
![image](https://user-images.githubusercontent.com/8340890/176286756-406eea21-ef07-4e4d-b904-b7207bd4f007.png)

### POST response - Firefox
![image](https://user-images.githubusercontent.com/8340890/176286912-ee1debcc-a070-47cd-bf22-a80c3143f547.png)

### OPTIONS Headers In Chromium
![image](https://user-images.githubusercontent.com/8340890/176287952-bb43304e-647e-4ce2-a6d2-982f719553c1.png)

### POST Headers In Chromium
![image](https://user-images.githubusercontent.com/8340890/176288061-a9dc6536-7115-4383-baa9-c2f9c609c94e.png)

### OPTIONS Response - Chromium
![image](https://user-images.githubusercontent.com/8340890/176288342-21f2792c-998c-44eb-84b1-bc8dd84d9f48.png)

### POST Response - Chromium
![image](https://user-images.githubusercontent.com/8340890/176288270-9bb5462c-319d-424e-b14c-7e32ba17f4f0.png)


> What does happen if you copy the request as CURL and execute it in a terminal?

## CURL OPTIONS 
```
curl 'https://xxx.apm.us-west-2.aws.cloud.es.io/intake/v2/rum/events' -X OPTIONS -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Access-Control-Request-Method: POST' -H 'Access-Control-Request-Headers: content-type' -H 'Referer: http://localhost:3000/' -H 'Origin: http://localhost:3000' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: cross-site' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' --verbose
*   Trying 52.26.59.44:443...
* TCP_NODELAY set
* Connected to xxx.apm.us-west-2.aws.cloud.es.io (52.26.59.44) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.us-west-2.aws.elastic-cloud.com
*  start date: May 18 23:32:14 2022 GMT
*  expire date: Aug 16 23:32:13 2022 GMT
*  subjectAltName: host "xxx.apm.us-west-2.aws.cloud.es.io" matched cert's "*.apm.us-west-2.aws.cloud.es.io"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55da4fc7b2f0)
> OPTIONS /intake/v2/rum/events HTTP/2
> Host: xxx.apm.us-west-2.aws.cloud.es.io
> user-agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0
> accept: */*
> accept-language: en-US,en;q=0.5
> accept-encoding: gzip, deflate, br
> access-control-request-method: POST
> access-control-request-headers: content-type
> referer: http://localhost:3000/
> origin: http://localhost:3000
> connection: keep-alive
> sec-fetch-dest: empty
> sec-fetch-mode: cors
> sec-fetch-site: cross-site
> pragma: no-cache
> cache-control: no-cache
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 502 
< content-type: application/json; charset=UTF-8
< x-cloud-request-id: mrDsZNv6RTmZWGS8ATQBwQ
< x-found-handling-cluster: xxx
< x-found-handling-instance: instance-0000000012
< content-length: 63
< date: Tue, 28 Jun 2022 21:14:37 GMT
< 
{"ok":false,"message":"The instance rejected the connection."}
* Connection #0 to host xxx.apm.us-west-2.aws.cloud.es.io left intact
```

## CURL POST
```
curl 'https://xxx.apm.us-west-2.aws.cloud.es.io/intake/v2/rum/events' -X POST -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0' -H 'Accept: */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/x-ndjson' -H 'Content-Length: 15244' -H 'Origin: http://localhost:3000' -H 'Connection: keep-alive' -H 'Referer: http://localhost:3000/' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: cross-site' --verbose
*   Trying 54.212.23.110:443...
* TCP_NODELAY set
* Connected to xxx.apm.us-west-2.aws.cloud.es.io (54.212.23.110) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=*.us-west-2.aws.elastic-cloud.com
*  start date: May 18 23:32:14 2022 GMT
*  expire date: Aug 16 23:32:13 2022 GMT
*  subjectAltName: host "xxx.apm.us-west-2.aws.cloud.es.io" matched cert's "*.apm.us-west-2.aws.cloud.es.io"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55b27be3e2f0)
> POST /intake/v2/rum/events HTTP/2
> Host: xxx.apm.us-west-2.aws.cloud.es.io
> user-agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0
> accept: */*
> accept-language: en-US,en;q=0.5
> accept-encoding: gzip, deflate, br
> content-type: application/x-ndjson
> content-length: 15244
> origin: http://localhost:3000
> connection: keep-alive
> referer: http://localhost:3000/
> sec-fetch-dest: empty
> sec-fetch-mode: cors
> sec-fetch-site: cross-site
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 250)!
< HTTP/2 502 
< content-type: application/json; charset=UTF-8
< x-cloud-request-id: WAfOi6kaR4iBJvXmLcDxkg
< x-found-handling-cluster: xxx
< x-found-handling-instance: instance-0000000012
< content-length: 63
< date: Tue, 28 Jun 2022 21:16:55 GMT
< 
{"ok":false,"message":"The instance rejected the connection."}
* Connection #0 to host xxx.apm.us-west-2.aws.cloud.es.io left intact
```

> One other thing that might be great to do is to test the endpoint in an isolated way, for instance:
> 
> ```
> <!DOCTYPE html>
> <html>
>     <head>
>         <script src="https://unpkg.com/@elastic/apm-rum@5.12.0/dist/bundles/elastic-apm-rum.umd.min.js"></script>
>     </head>
>     <body>
>         Hello, this is a local app with the RUM agent injected
>         <script>
>             elasticApm.init({
>                 serviceName: 'your-service-name',
>                 serverUrl: 'your-server-url',
>             })
> 
> 
>             elasticApm.observe('transaction:end', (tr) => {
>                 console.log("tr", tr)
>             })
>         </script>
>     </body>
> </html>
> ```

I tried with this suggestion and the situation is the same! 

> 
> Other that you might check is:
> 
> * What does happen if you try to restart the deployment? Does it work?

We just restarted and the problem persists.

We suspect the response from CURL: `{"ok":false,"message":"The instance rejected the connection."}`. 
When we try with `GET` to `serverUrl`, the response is the same... 

![image](https://user-images.githubusercontent.com/8340890/176295649-0a9269fa-c01f-448b-8d64-c04da1db41d3.png)


I hope this information helps us to find the problem.

Thank you very much!

Francisco

**Comment by devcorpio** [comment]
Hi @fsalazarh,

Thanks again for the thorough response!

The `{"ok":false,"message":"The instance rejected the connection."}` is indeed the issue!

Given that the problem is related to your concrete deployment you will need to open a SHD, **it's pretty important that you reference this issue when doing that**. If you have not opened a case before, the following are the possible ways to do it:

- Following the steps from elastic cloud docs: https://www.elastic.co/support/welcome/cloud#when-should-i-open-a-case
- Using the form available in your elastic cloud account:

<img width="258" alt="Screenshot 2022-06-29 at 11 29 46" src="https://user-images.githubusercontent.com/15065076/176403293-303fb429-6ce4-4330-aa23-86b6d482e2e9.png">

and

<img width="833" alt="Screenshot 2022-06-29 at 12 16 27" src="https://user-images.githubusercontent.com/15065076/176412985-180166ae-7f1a-4389-9937-a470e1e76344.png">


Let me know if you need anything else from my side

Thanks,
Alberto

**Comment by reny122010** [comment]
Hi everyone, what'up? 

i'm have a problem with integrations lib @elastic/apm-rum-angular

Sending the request events to apm server, i'm not receiving response of the request and in console of browser show info of CORS Error.

Somebody have a solution of the problem?

**Comment by fsalazarh** [comment]
Hi @devcorpio,

I opened a support case and the APM engineering team told me that there were many values in the agent policy that were wrong (we suspect that after a version update in the APM agent it was corrupted). They recommended reinstalling the apm fleet policy via this [script](https://gist.github.com/marclop/d37d61e5bb7f6c91d3943952bb0abddd), and that resolved the issue.

Thank you very much for the support.

Francisco
