### ISSUE TITLE
infomations of the request headers

### ISSUE THREAD

**Issue by zhaoShijuan** [elastic/apm-agent-rum-js#1264]
Hi, we try to add infos of a request headers to the 'external' span to through overwrite the 'setRequestHeader' method, but we can't associate the request header information with the corresponding span. What can we do?

**Comment by devcorpio** [comment]
Hi @zhaoShijuan,

Thank you for using the RUM agent!!

I would need more info in order to help you properly.

Questions:

1. Are you creating the "external" span [manually](https://www.elastic.co/guide/en/apm/agent/rum-js/master/span-api.html)? or is it being created automatically by the agent?

2. What do you mean with "overwrite the 'setRequestHeader' method"? Are you overwriting the native API of the XHR object or are you using the method to add the headers? 

3. Could you share the code you have written to achieve the span-header association?


Let me share two examples that may help you somehow, although they assume scenarios that might not be yours, so please, when you have time share with us the information requested above.

I'm also going to assume that your website performs network requests with [XHR](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) rather than with [Fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API). (since you mentioned setRequestHeader which belongs to XHR)

<ins>**Example that assumes that span is created manually:**</ins>

```
                const transaction = elasticApm.startTransaction('test', 'custom')
                const url = 'http://localhost:3000/api_test_2'
                const httpSpan = transaction.startSpan('GET ' + url, 'external.http')

                const xhr = new XMLHttpRequest()
                xhr.open('GET', url);
                xhr.onload = function () {

                    httpSpan.addLabels({ 'x-custom-header': "value", 'x-custom-header-2': "value2"})

                    httpSpan.end()
                    transaction.end()
                }
                xhr.send(null)
```

On the example above you can see how I added [labels](https://www.elastic.co/guide/en/apm/agent/rum-js/current/span-api.html#span-add-labels) that correspond to custom headers.

Kibana provides that information when seeing the details of the span

<img width="523" alt="Screenshot 2022-08-01 at 13 04 47" src="https://user-images.githubusercontent.com/15065076/182134840-9a4dfa81-f8a4-40a5-ac10-cd4be0b81b26.png">

Labels:

<img width="727" alt="Screenshot 2022-08-01 at 13 06 06" src="https://user-images.githubusercontent.com/15065076/182135228-c6da28e2-f799-4b41-8292-be11bbc5229b.png">


<ins>**Example that assumes that span is created automatically:**</ins>

You can leverage the `transaction:end` event to extract the span you are mentioning:

```
elasticApm.observe("transaction:end", tr => {
   if (tr && tr.type === "the type of your transaction") {
      const [mySpan] = tr.spans
                       .filter(span => span.type === 'external' && span.context.http.url === 'your-endpoint-url')

                        if (!mySpan.context.tags) {
                            mySpan.context.tags = {}
                        }

                        mySpan.context.tags['x-custom-header'] = 'value'
   }

})
```

To be honest, I wouldn't you to recommend to do that since relies on internal API properties and you might have issues in future versions of the RUM agent. Although, if for you it's crucial to have the headers on the span that's the way.


--

Bear in mind that you can also associate the headers to the [transaction](https://www.elastic.co/guide/en/apm/agent/rum-js/current/transaction-api.html#transaction-add-labels), too



Thanks,
Alberto

**Comment by zhaoShijuan** [comment]
Sorry for taking so long to reply！Below is the answer to your questions:
1. The span is created automatically by the agent

2. We want to get the headers

3. We added the following code to `xhr-patch.js`, `XHR_REQUEST_HEADER` is a constant

```
  const setRequestHeaderNative = XMLHttpRequestPrototype.setRequestHeader
  XMLHttpRequestPrototype.setRequestHeader = function() {
    const args = arguments
    this[XHR_REQUEST_HEADER] = {
      ...this[XHR_REQUEST_HEADER],
      [args[0]]: args[1]
    }
    setRequestHeaderNative.apply(this, args)
  }
```

**Comment by devcorpio** [comment]
Hi @zhaoShijuan,

Thanks for providing those details!

Overwriting setRequestHeader will not add the header you want to the "external" span.

--

Since the span is created automatically by the agent the most recommended way you have to add custom information on the fly is using [elasticApm.observe](https://www.elastic.co/guide/en/apm/agent/rum-js/5.x/agent-api.html#observe).

I don't know the details of your endpoint, but let me put an example with an arbitrary one:

**Example:**
- endpoint: http://localhost:3000/api_test_2
- header name: "hello"
- header value: "world"

RUM agent allows you to add custom information via [labels](https://www.elastic.co/guide/en/apm/agent/rum-js/5.x/span-api.html#span-add-labels). 

```
   elasticApm.observe("transaction:end", tr => {
          const externalSpans = tr.spans.filter(span => {
             return span.type === 'external' && span.context.http.url.includes("api_test_2")
          })

            externalSpans.map(span => {
                    span.addLabels({ "hello": "world" })
           })
    })
```

As you can see at the code above, I'm observing the end of the transaction and:

- extracting all the external spans of such transaction and filtering by the endpoint
- add the header info via labels

The code is just an example, but it's quite lightweight and malleable, so you can modify to meet your requirements if needed

Doing so, you will be able to see the labels on the span details:

<img width="982" alt="Screenshot 2022-09-12 at 17 18 56" src="https://user-images.githubusercontent.com/15065076/189692320-fdcf4633-ae24-454e-8745-6c9d53ca363f.png">

You can search spans with such label via Kibana Discover:

<img width="237" alt="Screenshot 2022-09-12 at 17 22 32" src="https://user-images.githubusercontent.com/15065076/189693015-ff9f6a2e-9ee6-4e12-9a2a-b60d998f2cdb.png">


and 

<img width="439" alt="Screenshot 2022-09-12 at 17 28 35" src="https://user-images.githubusercontent.com/15065076/189694297-2f663954-dadc-46b5-9422-2e28033d036a.png">


Thanks,
Alberto

**Comment by devcorpio** [comment]
Hi @zhaoShijuan,

Have you managed to get this working?

Thanks,
Alberto
