### ISSUE TITLE
In the same window, iframe embedded pages produce different sessions

### ISSUE THREAD

**Issue by dragonTour** [elastic/apm-agent-rum-js#1274]
In some older systems, the IFrame embedding subsystem was used. User sessions are stored in sessionStorage and cannot use the same session.
We believe that the same window should belong to the same user.

**Comment by dragonTour** [comment]
> In some older systems, the IFrame embedding subsystem was used. User sessions are stored in sessionStorage and cannot use the same session. We believe that the same window should belong to the same user.

self-assigned

**Comment by dragonTour** [comment]
self-assigned

**Comment by devcorpio** [comment]
Hi @dragonTour,

Thanks for taking the time on creating this issue!

Since [sessionStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) is isolated by origin you cannot access from the iframe to the sessionStorage data of the top window (if their origins differ.). Localstorage also behaves the same way since also complies the [same-origin](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) policy.

Little example:

top window origin:  http://localhost:3000
iframe embedded origin: http://localhost:3001

<img width="553" alt="Screenshot 2022-09-08 at 11 18 56" src="https://user-images.githubusercontent.com/15065076/189085160-940df293-2515-492a-bbf9-a1aeb595e72f.png">

As you can see at the screenshot above there is an instance of sessionStorage by each origin.

It's also important to mention that we are working on revamping how the user sessions work within the RUM agent and the current behaviour is not officially documented either. Because of that, I don't advocate for making a change on the RUM agent. Instead what I strongly recommend is to solve this inconvenient directly from your codebase. I would like to help you with the solution:

**Approach 1:**

The "easiest" one (ofc, I understand that it might not be possible in your situation) is to make sure that the iframe origin is the same one than the top window, for instance:

- top window: http://localhost:3000
- iframe: http://localhost:3000/iframe-site/iframe.html 

Doing so, you will be able to retrieve the information you need from the storage


**Approach 2:**

For instance:

Note: I recommend to read about [this] article about (https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#security_concerns
) security practices

**main-window:** (http://localhost:3000)

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>top window</title>

    <head>
        <script src="https://unpkg.com/@elastic/apm-rum@5.11.1/dist/bundles/elastic-apm-rum.umd.min.js"></script>
        <script>
            elasticApm.init({
                serviceName: "iframe-approach-2",
                serverUrl: "http://localhost:8200/",
                session: true
            })
        </script>
    </head>
</head>
<body>
    top window content

    <script>
        // top window listening for messages
        window.addEventListener("message", function (event) {
            //I recommend to check the origin, too. Please review the security guide I linked on the github issue
            if (event.data.type === 'retrieve-session-data') {
                const message = {
                    type: 'retrieve-session-data-response',
                    data: localStorage.getItem("elastic_apm_config") // bear in mind that it might be in localStorage instead, please check
                }

                // replying back to the iframe with the session data
                event.source.postMessage(message, 'http://localhost:3001'); // the second argument refers to the iframe origin
            }
        });
    </script>
    <iframe src="http://localhost:3001/iframe-isolation/iframe.html"></iframe>
</body>
</html>
```

**iframe:** (http://localhost:3001)

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    iframe content

    <input type="button" id="click-button" value="retrieve session info">
    <div id="session-panel">

    </div>
    <script>
        document.getElementById('click-button').addEventListener("click", (event) => {
            const topWindow = window.top

            const message = {
                type: 'retrieve-session-data'
            }

            // ask for the session info the the top frame
            topWindow.postMessage(message, 'http://localhost:3000') // the second parameter refer to the top window origin
        })


        // Listen to the top window response
        window.addEventListener('message', (event) => {
            // Receiving the session info. I recommend to check the  origin, too.
            // Please review the security guide I linked on the github issue
            if (event.data.type === 'retrieve-session-data-response') {
                console.log("event", event.data)
                document.getElementById('session-panel').innerText = event.data.data
            }
        })
    </script>
</body>
</html>
```

I'm attaching a zip file (includes the **nodejs** server so you can test it easily)

[iframe-isolation-approach-2.zip](https://github.com/elastic/apm-agent-rum-js/files/9526026/iframe-isolation-approach-2.zip)

1. npm install
2. npx nodemon index.js

The following video shows how it work:

https://user-images.githubusercontent.com/15065076/189100365-09be8b0c-437b-4fa5-9cb3-1bb66cc796ef.mov


--

Let me know if this helps you.

Thanks,
Alberto

**Comment by dragonTour** [comment]
Let's make things a little easier.

We don't have to make the IFrame use the same session, we just need to make the data we send to the service use the same session.

Therefore, we can have all actions sent to the service done by the top page.

The data collected in this way is all from the same session.

**Comment by devcorpio** [comment]
Great to see that you found a good approach to solve your scenario 🚀 

I'm closing the issue then, if you need anything else, let us know

Cheers,
Alberto
