### ISSUE TITLE
Incorrect transaction duration for pages after redirect

### ISSUE THREAD

**Issue by trainings** [elastic/apm-agent-rum-js#1279]
We use token handler pattern for enforcing authentication for web applications.
Steps:
1. user types abc.xxx.com and sends a request
2. on the server side it checks for the presence of a token in the cookie. if there is no token, the user is redirected to authorization service auth.xxx.com
3. user enters his credentials
4. user redirected back to the abc.xxx.com

everything is standard, but:

page load transaction measured from point 1 (not 4)
on the sample of a transaction, gaps for items 2 & 3

**Comment by devcorpio** [comment]
Hi @trainings,

Thanks for reaching out!

Bear in mind that the RUM **[page-load](https://www.elastic.co/guide/en/apm/agent/rum-js/current/supported-technologies.html#page-load-metrics)** transaction will end just after the browser fires the page [load event](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event). 

The agent do not keep state between **full-page** refreshes which means that every page will have each own page-load transaction. 
Important to mention that it's possible to [disable](https://www.elastic.co/guide/en/apm/agent/rum-js/current/configuration.html#disable-instrumentations) the page-load instrumentation so you can **start** and **end** such transaction [manually](https://www.elastic.co/guide/en/apm/agent/rum-js/5.x/custom-transactions.html), that tends to be common in SPAs given that you might want to decouple "my SPA is fully loaded/bootstrapped" from the load event the browser fires. On your particular scenario this might not help since it seems that you are doing redirects that force the browser to fully refresh.

 In a future version of the agent we will introduce the concept if user sessions which will provide (among other things) with the possibility of seeing every page-load transaction grouped together under the same session id.


Thanks,
Alberto

**Comment by trainings** [comment]
I feel like I've been misunderstood.
Now, if an anonymous user, in the process of gaining access to a web page, goes to an external service (e.g. keycloak) for authentication, then all redirects (to keycloak and back to my service callback, etc.) time are counted as a transaction time.

For example - I have a page with page-load-time 3sec.
And we have the following:
User is opening a browser and typing xxx.com and sending it
My service processes the request and checks that the user isn't authenticated
My service redirect (302 http code) the user to the IDP (keycloack) on another domain auth.com
The user gets to this page and enters his password there (5 sec) and submits it
Auth service verifies user credentials and redirect user back to the xxx.com/callback with a authorization code
User goes to xxx.com/callback, xxx application completes the phase post-login (extracts jwt token from auth service) and only after that redirects the user to the originally requested page (xxx.com)

What we have:
I have a page with page-load-time 3sec (for authenticated users)
But for users who was not authenticated before and who should pass authentication transactions time will be:
5sec (enter credentials) + 3sec (real page load time) + some time for redirects
Transaction duration will be: 8-9 sec instead of 3

This negatively affects the metric
This distorts the metric, because my application has not become worse
I can't figure out on my own how much time the user now spends on going through the authentication path

**Comment by litwin90** [comment]
Hello everyone, seems we have the same problem 
Are there any updates on this issue?

**Comment by litwin90** [comment]
As I could see the problem could be located here
![image](https://user-images.githubusercontent.com/33813087/203848859-20938d88-3fdc-4968-8927-9a95c045a4ea.png)

I mean that earliest span is highly like being got from Performance observer (which initiated earlier then the final navigation in case of auth with redirections)

![image](https://user-images.githubusercontent.com/33813087/203849321-48131c56-413f-4d68-8f86-77c20d4d30d8.png)

**Comment by TELEUZI** [comment]
Hi everyone, our team met the same problems, what is the current state of issue and may be there is some temporary solution?

**Comment by devcorpio** [comment]
Hi everyone,

The bug has been found. 

Unlike createNavigationTimingSpans, when we create createResourceTimingSpan we are NOT substracting [fetchstart](https://w3c.github.io/navigation-timing/#dom-performancetiming-fetchstart) from the span **start** and **end** properties. In a nutshell, we are not creating these spans relative to when the current page has been loaded.

This is important since performance entry times include the time spent before the redirection happened.

Example (node.js server):

http://localhost:3000/the-server-will-redirect-this.html

```app.get('/the-server-will-redirect-this.html', (req, res) => {
  setTimeout(() => {
    res.redirect("http://localhost:3000/index.html")
  }, 2000)
})
```
Once the redirection is performed, we can see how the navigation spans are correctly set:

<img width="359" alt="Screenshot 2022-11-28 at 13 37 09" src="https://user-images.githubusercontent.com/15065076/204279455-a2c6e780-ccd4-4cfa-ad04-db4186aa2e44.png">

However, the resource timing spans are not:

<img width="480" alt="Screenshot 2022-11-28 at 13 37 53" src="https://user-images.githubusercontent.com/15065076/204279621-ee96d4d4-7a5f-4c41-bfbd-8f9c551c82c3.png">


When skipping the redirection, we can see how the resource timing spans are correctly set:

<img width="468" alt="Screenshot 2022-11-28 at 13 39 16" src="https://user-images.githubusercontent.com/15065076/204279892-5e15728b-b354-4197-954d-7137279a8fd7.png">

Thanks,
Alberto

**Comment by trainings** [comment]
Hi all!

Are there any news and when is it planned to fix this problem?

Last release was June 14th,
Does it mean that the service/agent is dead and it's time to look at an alternative?

**Comment by oxcafedead** [comment]
Hi @devcorpio!
It seems that the issue is clear now, but is the fix ready or some contribution wanted? Maybe you could provide some estimated time when this going to be fixed?
In your last comment, you mentioned that:
> We will give priority to this fix
Thanks!

**Comment by litwin90** [comment]
Would be great to get an update on this issue
@devcorpio

**Comment by drewpost** [comment]
Just a quick update on this. We are aiming to get this issue resolved and shipped in the next couple of months alongside several other RUM agent improvements.

**Comment by devcorpio** [comment]
Hi everyone,

The team is currently working on this, too.

To give you a little more context, after further analysis, we don't. consider was not a bug, but an important enhancement. We will start adding an additional span named "Redirect" (if applicable), and you will be able to see why the transaction lasted more than usual:

E.g.

<img width="1055" alt="Screenshot 2023-07-07 at 12 11 22" src="https://github.com/elastic/apm-agent-rum-js/assets/15065076/5e861fdf-7aea-4bc7-8af1-3717a0072a8c">

Thanks,
Alberto

**Comment by oxcafedead** [comment]
@devcorpio can we make a difference for redirects within the same site/origin and redirects to third party systems?
I mean, including a same-origin redirect into a transaction does make sense to me, but for third party systems this is not something we can control at our end. For example, I found in [navigation timing API](https://w3c.github.io/navigation-timing/#PerformanceResourceTiming) the following words:
> Though `redirectStart` and `redirectEnd` are exposed in `PerformanceResourceTiming`, they have a different meaning in Navigation Timing, where they return zero for navigations with cross-origin redirects.

If I understand right, navigation timing browser API should return 0 for redirects to cross-origin, can we have similar behavior?

**Comment by fonshirin** [comment]
@devcorpio, maybe we can use PerformanceNavigationTiming interface instead of PerformanceNavigationTiming to create navigation spans. PerformanceNavigationTiming uses relative timing values instead of timestamps so its timings will be aligned with Resource Entry timings, LCP timings, etc. In case of cross-domain redirect PerformanceNavigationTiming properties values will also include the duration of the redirect. So we will be able to detect that some action was happened before the navigation events were really triggered. In this case we will be able to draw this action as the first span in the waterfall, like in the example of the future fix provided by you.

Thx.

**Comment by fonshirin** [comment]
> @devcorpio, maybe we can use PerformanceNavigationTiming interface instead of PerformanceTiming to create navigation spans. PerformanceNavigationTiming uses relative timing values instead of timestamps so its timings will be aligned with Resource Entry timings, LCP timings, etc. In case of cross-domain redirect PerformanceNavigationTiming properties values will also include the duration of the redirect. So we will be able to detect that some action was happened before the navigation events were really triggered. In this case we will be able to draw this action as the first span in the waterfall, like in the example of the future fix provided by you.
> 
> Thx.

Dear @devcorpio, and how about the fix for cross-domain redirect?
Please see my previous comment above in quote.

Thank you in advance.
