### ISSUE TITLE
Instrumenting with `fetch` enabled removes the `Origin` header, among others

### ISSUE THREAD

**Issue by eaardal** [elastic/apm-agent-rum-js#1281]
Hi I'm currently exploring apm rum and how to set it up for our website, but are having some issues when the `fetch` instrumentation is enabled, namely that all our own outgoing API calls fails with CORS error. This is _not_ CORS to apm-server but CORS in our own API that is failing.

Said simply, if the `fetch` instrumentation is enabled, our `Origin` header, along with many others, is gone from all outgoing requests.

Here is an API request normally:
![Screenshot 2022-09-22 at 15 58 50](https://user-images.githubusercontent.com/2316274/191945276-5cdae905-d79c-46f1-b79a-c4d6bb383d91.png)

Here is the same API request with fetch instrumented/patched:
![Screenshot 2022-09-23 at 12 51 28](https://user-images.githubusercontent.com/2316274/191945562-b5cadc06-ee9a-47af-ba06-a5424d6d92f8.png)

As you can see, I have a custom header that _is_ being carried over when fetch is patched, but `Origin` (and many others) is not, so our CORS fails. This is the preflight request that failed so it would be a bit different than a "normal" request, but still, we need that Origin header.

I've traced it down to [this line](https://github.com/elastic/apm-agent-rum-js/blob/main/packages/rum-core/src/common/patching/fetch-patch.js#L78) and confirmed that `Origin` is set in `init` but I can't read it back out in `request` after that line

![Screenshot 2022-09-23 at 12 38 46](https://user-images.githubusercontent.com/2316274/191946193-9cba3acc-6374-4235-a4ed-5012f0edd458.png)

Some context info:
- I'm running elastic, kibana and fleet locally using the docker-compose from https://github.com/elastic/apm-server and running apm-server by running [runapm](https://github.com/elastic/apm-server/tree/main/systemtest/cmd/runapm) in the same repo, so this is all on my machine/localhost except the API I'm calling.
- Other instrumentations (`page-load`, `history`, `eventtarget`, `error`) are collected correctly out of the box and showing up in my APM traces in Kibana on localhost.

Let me know if you need more info :)

**Comment by devcorpio** [comment]
Hi @eaardal,

Thanks for the detailed message, much appreciated!

Just commenting to let you know that we are looking at the issue and will let you know our findings shortly.

Thanks,
Alberto

**Comment by devcorpio** [comment]
Hi @eaardal,

The reason of the CORS error seems to be on the **traceparent** header that the agent adds automatically when instrumenting fetch.

This link explains what headers you should have into account when configuring CORS:
https://www.elastic.co/guide/en/apm/agent/rum-js/current/distributed-tracing-guide.html#server-configuration

One quick way to confirm that the problem comes from the traceparent header is:

1. to enable fetch instrumentation again
2. to disable [distributed tracing](https://www.elastic.co/guide/en/apm/agent/rum-js/current/configuration.html#distributed-tracing)

--

Given that the agent is adding the header to a cross-origin request I'm assuming that you have also set the [origins](https://www.elastic.co/guide/en/apm/agent/rum-js/current/configuration.html#distributed-tracing-origins) config option. I'm saying this because the agent, by default, only sends it to [same-origin](https://www.elastic.co/guide/en/apm/agent/rum-js/current/distributed-tracing-guide.html#enable-cors) requests. 

For everything I've mentioned above, it seems that a little change is needed on the CORS configuration of your API.


Let me know if this helps you,

Thanks,
Alberto

**Comment by eaardal** [comment]
Thanks @devcorpio, I had indeed missed the step with allowing `traceparent` and `tracestate` headers in our CORS settings. It seems to work fine now 👍 Closing the issue for you
