### ISSUE TITLE
unable to configure apmRequest in init

### ISSUE THREAD

**Issue by Devikajn** [elastic/apm-agent-rum-js#1320]
AgentConfigurationOptions doesn't have apmrequest key. I am using  apm javascript agent version 5.12.0

**Comment by devcorpio** [comment]
Hi @Devikajn,

Thanks for reaching out!

The existing options that you can use when initializing the RUM agent are available here: https://www.elastic.co/guide/en/apm/agent/rum-js/current/configuration.html

One of those options is [apmRequest](https://www.elastic.co/guide/en/apm/agent/rum-js/current/configuration.html#apm-request)

Let me know if this helps you

Thanks,
Alberto

**Comment by Devikajn** [comment]
Hi @devcorpio I am using version 5.x but still I am not getting apmReq as an option

**Comment by devcorpio** [comment]
Hi @Devikajn,

Could you share the snippet you are using for initializing the agent?

Thanks,
Alberto

**Comment by devcorpio** [comment]
Hi @Devikajn,

I see what it's happening, apologies for the confusion. The RUM agent including the [option](https://github.com/elastic/apm-agent-rum-js/pull/1254) on the types file has not been released. That's why you are not seeing it.

You can use that option anyway (you will need to silent typescript) even if typescript doesn't autocomplete it.

```
import { init as initAPM } from '@elastic/apm-rum';

initAPM({
    serverUrl: "http://localhost:8200",
    // @ts-ignore
    apmRequest: ({ xhr, url, method, payload, headers }) => {
        
    },
    serviceName: "myservice"
})

```


Thanks,
Alberto

**Comment by devcorpio** [comment]
Hi @Devikajn,

I'm closing the issue. Please, If you need further help let us know.

Thanks,
Alberto
