### ISSUE TITLE
Custom spans not getting sent from agent

### ISSUE THREAD

**Issue by geekysam7** [elastic/apm-agent-rum-js#1425]
Hi, I've a use case where we're updating spans under a transaction via a function call.

Steps:
- Function call to create a transaction.
- Function call to add span to the transaction (end the span there itself)
- Function call to end the transaction.

In this case spans do get attached to the transaction but I don't see them on the apm services page. Can you please letme know what am I doing wrong here?

```js
import apmRum from '../../rum';

export const getApmRumInstance = () => apmRum;

export const getCurrentTransaction = () => apmRum.getCurrentTransaction();

export const startTransaction = (name, type, labels) => {
    const transaction = apmRum.startTransaction(name, type, { managed: true });
    transaction.startSpan(name, type, { blocking: true });
    if (labels) {
        transaction.addLabels(labels);
    }
    return transaction;
};

const addSpansToTransaction = (t, spansToAdd = 10) => {
    for(let i = 0; i < spansToAdd; i++) {
        const s = t.startSpan('Span - ' + i);
        s.end();
    }
}

export const endTransaction = () => {
    const transaction = getCurrentTransaction();
    if (!transaction) {
        return;
    }

    addSpansToTransaction(transaction);

    const activeSpans = transaction._activeSpans || {};
    Object.values(activeSpans).forEach(span => span.end());
    // all spans visible in log & api call is success
    console.log(transaction, transaction.spans, transaction.ended);
    transaction.end();
}

```

Screenshot:

<img width="1123" alt="Screenshot 2023-09-07 at 4 04 02 AM" src="https://github.com/elastic/apm-agent-rum-js/assets/44406218/8588886e-bb76-46a3-821f-bfbc49ce64ca">

I've one more doubt here:

when I do it like this:

```
const transaction = apmRum.startTransaction('Txn', 'custom', { managed: true });
const span = transaction.startSpan('Blocking Span', 'custom', { blocking: true });

fetch(...); // POST url1 
fetch(...); // GET url2

span.end();
transaction.end();
```

<img width="1138" alt="Screenshot 2023-09-07 at 4 08 39 AM" src="https://github.com/elastic/apm-agent-rum-js/assets/44406218/9f5bea5a-07b7-4e8c-a23a-6caf5cdb5d4c">

This seems to work, adding the fetch api calls to the spans of current transaction. But in the same case if I do it like this:

```
startTransaction('Txn', 'custom');
fetch(...); // POST url1 
fetch(...); // GET url2

endTransaction();
```

<img width="1154" alt="Screenshot 2023-09-07 at 4 08 26 AM" src="https://github.com/elastic/apm-agent-rum-js/assets/44406218/5abe54e0-9cff-456a-bbda-b715c2affc80">

The api calls are not monitored, only the blocking span is getting monitored. Why is this happening??

**Comment by devcorpio** [comment]
Hi @geekysam7,

Thanks for including all these details!

> In this case spans do get attached to the transaction but I don't see them on the apm services page. Can you please letme know what am I doing wrong here?

`addSpansTransaction` creates a span and ends it right away. Because of that, the span's duration is 0. Bear in mind that spans with no duration (0) are discarded and not sent to APM. Make sure a lapse of time passes between the creation of a span and its ending.

If you add a listener to the [transaction:end](https://www.elastic.co/guide/en/apm/agent/rum-js/current/agent-api.html#observe) event you will see how those spans are not attached at that point. Example of snippet:

```
 elasticApm.observe("transaction:end", tr => {
   console.log("tr", tr)
 })
```

Additionally, if you follow the instructions detailed [here](https://www.elastic.co/guide/en/apm/agent/rum-js/current/troubleshooting.html#disable-events-payload-compression) you will be able to see RUM events payload sent to APM (which in this particular case will not include those spans). This will aid you with debugging as well

> But in the same case if I do it like this:
> 
> startTransaction('Txn', 'custom');
> fetch(...); // POST url1 
> fetch(...); // GET url2
> 
> endTransaction();
The api calls are not monitored, only the blocking span is getting monitored. Why is this happening??
> 

I've tested this and I'm unable to reproduce your scenario:

**Snippet I used:**

```
    startTransaction('Txn', 'custom');
     fetch("http://localhost:3000/api_test");
    fetch("http://localhost:3000/api_test_2");

    endTransaction()
```

**Output extracted from `transaction:end` event**

<img width="1091" alt="Screenshot 2023-09-07 at 11 44 36" src="https://github.com/elastic/apm-agent-rum-js/assets/15065076/da8cf186-d437-412f-828a-5976c584afb9">

**Content of the event sent to APM:**

<img width="996" alt="beacon-capture" src="https://github.com/elastic/apm-agent-rum-js/assets/15065076/393e6667-493d-49e8-9e75-bbc477bda8a0">

Are the spans associated with those API calls being attached to a different transaction perhaps? I recommend you use the two techniques shared above (`transaction:end` and `event/beacon inspection` to try to pinpoint what's going on)

Hope this helps you to identify where the issue is.

Thanks again for all the provided details!

Cheers,
Alberto

**Comment by geekysam7** [comment]
Thanks for reply @devcorpio and going through every detail.

It does seem to be the issue of ending span immediately, after adding a timeout in b/w and testing it's working as expected:

<img width="1129" alt="Screenshot 2023-09-07 at 3 58 48 PM" src="https://github.com/elastic/apm-agent-rum-js/assets/44406218/54a3854c-affd-49ba-9a95-dc35a45f8682">


Next thing I would like to ask is can we modify start and end time of span manually? We've a usecase where we want to store extra data along with the span and we handle them manually, sending start and end time.

**Comment by devcorpio** [comment]
Hi @geekysam7,

> Next thing I would like to ask is can we modify start and end time of span manually? 

yes, it's possible, for instance:


```
  const s = t.startSpan('Span - ' + i, "span-type" , { startTime: 45 });
  s.end(75);
```

You can see the signature of end [here](https://github.com/elastic/apm-agent-rum-js/blob/main/packages/rum/src/index.d.ts#L162) and the options for starting a span here: https://github.com/elastic/apm-agent-rum-js/blob/main/packages/rum/src/index.d.ts#L54

Cheers,
Alberto

**Comment by geekysam7** [comment]
Got it @devcorpio, this is very helpful. Thank you so much!

Also shouldn't we add these options and signature for end in docs as well? Will be really helpful for anyone looking to implement something similar.

**Comment by devcorpio** [comment]
that's a good point! back then this wasn't not documented for specific reasons. will raise this topic within the team and see if  we end up deciding to document it

Thanks!

**Comment by vigneshshanmugam** [comment]
> It does seem to be the issue of ending span immediately, after adding a timeout in b/w and testing it's working as expected:


You could work around these async activities if you are worried about losing them by either adding a block span Immediately which I see that you used on the first example. But just having two fetch calls, its basically a race, You can basically block the [transaction](https://www.elastic.co/guide/en/apm/agent/rum-js/current/transaction-api.html#transaction-block) which internally works same as the `blocking span` and release it once you are done with the instrumentation. 

Regarding the docs around `startTime`, the reason why we did not document those is because its easily possible to add arbitrary values that might break the UI and ends up causing confusion to the customers. Its for internal usecase where its mainly used for time skewing issues and for the testing purposes. Hope that helps.
