### ISSUE TITLE
`@elastic/apm-rum-angular` package is giving error in Angular 9

### ISSUE THREAD

**Issue by HanenBenYounes** [elastic/apm-agent-rum-js#1460]
Hi, i attempted to implement `@elastic/apm-rum-angular` package with `Angular v9.0.7` , but I got a few console warnings: 

```ERROR in node_modules/@elastic/apm-rum-angular/apm.service.d.ts:28:13 - error TS1005: '=' expected. 28 import type import * as ɵngcc0 from '@angular/core';           node_modules/@elastic/apm-rum-angular/apm.service.d.ts:29:29 - error TS1005: ';' expected 29 { AgentConfigOptions } from '@elastic/apm-rum';```

Any help would be appreciated.

**Comment by devcorpio** [comment]
Hi @HanenBenYounes,

Thanks for reaching out

I have a question:

What version of the `apm-rum-angular` are you using?

I'm asking this because the 3.x version is for Angular >= 12

If you want to use the integration in Angular 9 you will need to install apm-run-angular 2.x, please see additional information on this docs page:  https://www.elastic.co/guide/en/apm/agent/rum-js/current/angular-integration.html
<img width="856" alt="screenshot" src="https://github.com/elastic/apm-agent-rum-js/assets/15065076/39088273-50b0-47e3-b2be-1032da1c57b8">





Thanks,
Alberto
