### ISSUE TITLE
[docs] Add cross browser testing svg to docs

### ISSUE THREAD

**Issue by bmorelli25** [elastic/apm-agent-rum-js#244]
Since the cross browser testing information is just an svg, we can easily add it to the documentation.
[![Sauce Test Status](https://saucelabs.com/browser-matrix/elastic-apm-base.svg)](https://saucelabs.com/u/elastic-apm-base)
<br><sup>Cross Browser testing is provided by [Sauce Labs](https://saucelabs.com/)</sup>

The tougher question is: where? I know the [supported technologies](https://www.elastic.co/guide/en/apm/agent/js-base/current/supported-technologies.html) page is about instrumentation, but I think it makes the most sense to add it here. I'm thinking we could add a new subheading called "Supported platforms" - that way it's on its own page, but under the "supported tech" heading which is where people will probably look for it.

Thoughts?

**Comment by bmorelli25** [comment]
Alvaro brought up that this may be tougher to implement than I initially thought. Is there any way to version/tag the cross browser testing image so it accurately reflects compatibility by agent version?

@vigneshshanmugam @jahtalab

**Comment by jahtalab** [comment]
@bmorelli25 , 
Adding a subheading to supported technologies sounds good to me.

Re. The browser matrix badge, it is generated by sauce labs (the platform we use to run our tests across browser). Unfortunately sauce labs doesn't have the capability to generate these badges based on branch therefore it will always show the status of the last test.

I'm ok with just writing out a similar table manually in the asciidocs and making sure that we maintain it going forward. The rate of updates to this table should be fairly low since we only remove support for browsers on major versions.

if we really want to show something fancy, there are alternatives that can generate a similar svg, e.g. [badge-matrix](https://github.com/exogen/badge-matrix) which generates something like: 

![Browser matrix](https://badges.herokuapp.com/browsers?firefox=20,26&iexplore=!8,-9,10&googlechrome=49,62)

**Comment by bmorelli25** [comment]
Great! I'm leaning towards the asciidoc table as that sounds easiest, but if you want to help with a fancy badge-matrix solution, I'm cool with that too! Let me know what you'd prefer and I'll get a PR going.

**Comment by jahtalab** [comment]
I think we should do the easier approach which as you mentioned is having a table in the asciidoc 👍

**Comment by bmorelli25** [comment]
Perfect. I'll get a PR opened soon :)
