### ISSUE TITLE
Redact sensitive information from the http url

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#252]
Currently, the username and password can be leaked into the APM data when we capture http urls, e.g. http://username:password@@example.com.

**Comment by vigneshshanmugam** [comment]
This issue is not applicable to the RUM agent, The sensitive requests(with username and password in the URL) will be removed in the case of XMLHttpRequest and TypeError in the catch of Fetch spec. The only way user can make a request with credentials is through `Authorization` header and we don't log it in the RUM agent. 

With that said, I am going to mark it as N/A in the top level APM issue and close this issue.

**Comment by axw** [comment]
Thanks for the investigation and update!

**Comment by vigneshshanmugam** [comment]
I missed the case for XHR calls, since we capture the url during open method and not during send, the browser does take care of url reconstruction after open, But our patch captures the URL even before it. In this scenario, we need to remove the sensitive username and pass. I will open the issue again and add a PR for the same. 

Sorry @axw for the confusion.
