### ISSUE TITLE
APM server failure showing 404 error

### ISSUE THREAD

**Issue by Praseela23** [elastic/apm-agent-rum-js#258]
Hi,
      When start my application it showing Request Method:OPTIONS and 404 error.  I am getting these error "Access to XMLHttpRequest at 'http://rum.apm.kloudlearn.com/intake/v2/rum/events' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No '**Access-Control-Allow-Origin**' header is present on the requested resource". But i configured "Allow-Control-Allow-Origin" in my configuration file.

**Versions:** 
Elastic-search : 6.4.1
APM server : 6.4.1

Here the healthcheck endpoint is work showing 200 status code. But, I POST event endpoint is not created showing error 404.

 ![Screenshot from 2019-05-02 16-07-52](https://user-images.githubusercontent.com/47236348/57071565-7741c900-6cf8-11e9-85b2-546513f5f1a1.png)

![Screenshot from 2019-05-02 16-12-14](https://user-images.githubusercontent.com/47236348/57071528-58dbcd80-6cf8-11e9-8090-db82c40cfd6e.png)

**Comment by jahtalab** [comment]
Hi @Praseela23 , 

Thanks for using Elastic APM.

The current version of the RUM agent is only compatible with APM server version 6.5+. We have made many improvements since version 6.4 so I highly recommend to upgrade to the latest version. You might also find our [Agent/Server compatibility guide](https://www.elastic.co/guide/en/apm/get-started/current/agent-server-compatibility.html) useful.
