### ISSUE TITLE
Add support for boolean and number values for labels

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#272]
Currently, boolean and number values for labels are converted to their string representation before being added to the payload. However, with APM Server 6.7, the support for these value types has been [added to APM Server](https://github.com/elastic/apm-server/pull/1712). We should start sending the raw values for these types.

Please note that this is a breaking change for older versions of APM server (prior to 6.7) and we should update the documentation to reflect this.

-  [ ] We should add new tests for these

**Comment by felixbarny** [comment]
One way to get around making this a breaking change is to check the APM Server version and convert numbers and booleans to strings when connected to an APM Server < 6.7.
I guess it depends on how urgent the need to offer these APIs are for the RUM agent and if it's worth the complexity. Especially for the RUM agent that would, however, mean another request to the APM Server just to check the version. That makes it less feasible for the RUM agent. Still wanted to mention it because it may be relevant for other agents.

**Comment by jahtalab** [comment]
Thanks @felixbarny , I think the cost of making an extra request just to check the APM server version, is too high. I don't see the breaking change as a big issue as long as we release it in a major version.

Plus, we can make documentation about how users can convert those values to string before calling the agent APIs, if the support for older versions is necessary.
