### ISSUE TITLE
Provide a way to prevent the Transactions from ending automatically

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#290]
We should provide a way for custom transactions to be ended manually. We can potentially make this the default and only automatically end the transaction if explicitly an option is provided to `startTransaction`

**Comment by vigneshshanmugam** [comment]
Had a quick discussion with @jahtalab @roncohen @felixbarny, Here is the summary

+ Figure out what will be the valuable metric types that we can showcase to the user in the context of RUM.
+ For Example - We can identify the time spent on Network(TTFB, DNS etc) and Resources(Images, CSS, JS) and add it to the breakdown
+ For non-sampled transactions, We can still calculate the aggregation either in agent side / APM server (Not decided yet)
+ The depth of the child in RUM is always 1, since we cannot differentiate between current frame and from other frames(iframe other domain). 
+ For single page transactions, The types would just be presented in terms of resources -> we can pick individual types as JS, CSS and Images. 

### Next steps
+ Go over some example transactions and figure out the self times based on the discussion as well as the algorithm presented on the proposal.
