### ISSUE TITLE
React router integration

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#301]
We need to provide an integration with react router to capture `route-change` transactions.

- [x] Document the API and provide examples of usage
- [x] fix Readme
- [x] Release 0.1.0
- [x] Implement the react-router integration
- [x] Implement the e2e tests
- [x] Implement unit tests

**Comment by ersel** [comment]
Hi @jahtalab , thanks for implementing this integration! I am just giving it a go on a project which uses `react-router`. Is there any reason why `render` prop is not supported?

https://medium.com/@ilovezcd/difference-between-render-and-component-prop-on-react-router-v4-368ca7fedbec

Some of our routes are using `render` instead of `component` and `ApmRoute` fails with a cryptic message saying can not read property display name of undefined.

**Comment by jahtalab** [comment]
Thanks @ersel for using the react-integration! Using the `render` property is not supported with `ApmRoute`, although, it should not throw an error. I have created #328 to address the error as well as update our docs. 

My suggestion is to instrument the route's top level component with `withTransaction`. 
Let me know if this works for you.

**Comment by ersel** [comment]
I have changed my render props to be components for now. Can you explain why `render` prop is not supported?

**Comment by jahtalab** [comment]
@ersel , The reason is mainly due to the fact that we need to integrate with the react component's life-cycle methods, therefore we need to have the component reference. Furthermore, the `render`, `children` properties can be used in complex situation therefore, it's better to use `withTransaction` to instrument the individual components.

Did you try to use `withTransaction` instead of using the component prop?
