### ISSUE TITLE
 How to tell the agent to send data back to the same server that sent the page ?

### ISSUE THREAD

**Issue by WassimDhib** [elastic/apm-agent-rum-js#327]
Hi,

I'd like to add the RUM script for an application which is hosted on the same server as the apm-server.

So, I have to add the following snippet to the top level html template:

```
<script src="dist/bundles/elastic-apm-js-base.umd.min.js"></script>
<script>
  elasticApm.init({
    serviceName: 'jpetstore',
    serverUrl: 'http://localhost:8200',
  })
</script>
```

The serverUrl has to be the same location as the server. But the location can change (at every deployement).
 How to tell the agent to send data back to the same server that sent the page ?

**Comment by vigneshshanmugam** [comment]
@WassimDhib Thanks for creating the issue. Currently it's not possible to set serverUrl to an empty string since that would allow the users to send the payload to `<window.location.origin>/serverUrlPrefix`, but `serverUrl` is a required parameter and hence you have to explicitly set it to non empty string. 

Ideally we can keep serverUrl as optional and allow for this behaviour. Will keep you posted here.

**Comment by vigneshshanmugam** [comment]
@WassimDhib For now you can configure the serverUrl to the window origin to post the payload data and pass your local prefix. 

```js
 elasticApm.init({
    serviceName: 'jpetstore',
    serverUrl: window.location.origin,
    serverUrlPrefix: '/blah'
  })
```

Hope this helps, Let us know if you need any other information.
