### ISSUE TITLE
Fix Saucelabs tests failures

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#400]
Currently we're seeing a lot of failures on saucelabs which are not related to the test itself. This affects our development process. We might need to adjust the concurrency of tests!

Happens mostly on IE 11 tests.

**Comment by vigneshshanmugam** [comment]
One thing we could do is to stop the matrix tests for Framework integrations on all stacks, So for `apm-rum-react`, we would test it only with a single stack(can be 7.3.0) and we would skip older stacks since we already test `apm-rum` and `apm-rum-core`. React integration as such doesn't do anything special so its not required.
