### ISSUE TITLE
sending transactions without spans to APM server

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/apm-agent-rum-js#461]
+ Currently the agent discards sending transactions without spans to the APM server 
+ Checking some of the discuss forum topics, users are interested in all the transactions and they are quite confused on why they are not seeing the transactions in the APM UI. 

Also, it might be helpful for the custom transactions since they might be able to understanding the response time of API calls or any other work during a period of time. 

Ex - https://discuss.elastic.co/t/has-anyone-been-able-to-create-custom-transaction-using-the-new-angular-integration/202072/3

**Comment by conlanpatrek** [comment]
I just ran into this issue and lost a bit of time to it while implementing some custom transactions around api calls. It's problematic because the documentation here https://www.elastic.co/guide/en/apm/get-started/current/transactions.html says that a transaction can have 0 spans associated with it. Then the documentation here https://www.elastic.co/guide/en/apm/agent/rum-js/current/custom-transactions.html doesn't note that the rum agent requires at least one span, or else it will get ignored.

I was only able to find out what was happening by reading the network log and then the rum agent source.

The workaround: Create a dummy span underneath the transaction *with the same start and end times as the transaction.*

My vote is definitely for sending transactions without spans to the server. What's the benefit of filtering them out?

**Comment by PaulMougel** [comment]
This can be pretty confusing indeed! We had the same issue as #509, and now I understand why 😃 
My vote is also for sending all transactions to the server.

**Comment by vigneshshanmugam** [comment]
Thanks for the feedback both, We have made a decision to send the transactions without spans to the server by introducing a config option and update the docs for the same.

**Comment by PaulMougel** [comment]
Adding to this conversation: we sometimes have empty transactions because they are ended too early by the RUM agent.

We are using the Vue integration, and it looks like the `afterEach` method of the router is called too early, before any HTTP call has been made by our components. It looks to me to be a lifecycle issue, but I'm not sure where the culprit lies. So sending transactions without spans only mask the issue… because we should anyway see full transactions with spans :-) Any advice there?

**Comment by vigneshshanmugam** [comment]
@PaulMougel Its a different problem and I agree with you that right now its a lifecycle issue and the agent cannot determine if there are any async dependencies for the current route since it can be lazy loaded. We are trying to address this problem and have a draft solution here #404

**Comment by PaulMougel** [comment]
Thank you for the quick answer; I will follow the linked issue then!
