### ISSUE TITLE
work with react-router is no response

### ISSUE THREAD

**Issue by AshoneA** [elastic/apm-agent-rum-js#500]
This is code sandbox, https://codesandbox.io/s/react-router-652z0, it requests event only reload the page. It won't requests event while I click the Link, is I missing something config?

**Comment by vigneshshanmugam** [comment]
The transactions are captured properly, but currently we don't report transactions without any spans to the server which is why you wont see the data in the APM UI #461

**Comment by AshoneA** [comment]
@vigneshshanmugam thanks for your answer. so should I write a `startSapn()` in the react component so that I can send the transaction to sever, is it right? Or it has another approach to do this?

**Comment by vigneshshanmugam** [comment]
If the underlying component has any dependencies like fetching data / static resources (JS/CSS) ,the agent would capture them as spans automatically and send it to the server. 

Since the component does not need any deps, the transaction does not contain any interesting spans and its discarded since its considered as not an interesting transaction and probably we can save some costs by not storing it.

**Comment by AshoneA** [comment]
@vigneshshanmugam yes, It's just a simple demo. In my project real environment, I found every time pushState will create a transaction, also I looked at source code, this project patched pushState.So it's good, but can I set the transaction's name so it‘s not all named Unknown?

**Comment by AshoneA** [comment]
Maybe there should have a config item like `pageLoadTransactionName` but It should be designed as a function that returns a string so that I can pass this function which returns location.pathname and so on.

**Comment by vigneshshanmugam** [comment]
Transactions names would be unknown for the history push state events and you can fix that with the location path by observing for the transaction start/end events. https://www.elastic.co/guide/en/apm/agent/rum-js/master/agent-api.html#observe

If a given transaction contains UNKNOWN till the lifetime of the transaction, you can change the name using the end event. 

```js
apm.observe('transaction:end', function (transaction) {
  if (transaction.type === 'UNKNOWN') {
    transaction.name = location.pathname
  }
})

```

Does this help? 

The reason why we don't use the `location.pathname` as default for the transactions is due to the cardinality of the transactions and how it would clutter the UI.

**Comment by AshoneA** [comment]
@vigneshshanmugam oh, awesome! It's work. I'm sorry for I didn't notice `apm.observe` API.Thank you very much!

**Comment by vigneshshanmugam** [comment]
@AshoneA No problem, Happy to help!
