### ISSUE TITLE
Vue route-change transaction discarded

### ISSUE THREAD

**Issue by LukeeeeBennett** [elastic/apm-agent-rum-js#509]
Hello, I noticed some vue `route-change` transactions are discarded because they have no spans. 
I have solved this by ensuring there is always a span that consequentially will measure the route visit as the transaction does.

```
let span
router.beforeEach((to, from, next) => {
  span = Vue.prototype.$apm.startSpan(to.path, 'route-visit')
  next()
})
router.beforeEach((to, from, next) => {
  if (span) span.end()
  next()
})
```

Does it make sense to do this? If so do you want it contributed upstream under a config option or would you prefer to keep that out of the plugins?

**Comment by vigneshshanmugam** [comment]
We have an issue already to track this behaviour and its not only common to vue alone. Right now we discard transactions without spans from sending to the server since users might not be interested in a single http call and also it helps reduce the storage size. 

But we were also leaning towards having a config option to send transactions without spans to the server since users might use that info to build graphs of a specific interesting transaction response times 

I am closing this in favor of #461
