### ISSUE TITLE
Cannot read property 'startSpan' of undefined

### ISSUE THREAD

**Issue by chriswoodley** [elastic/apm-agent-rum-js#589]
@jahtalab

given that the project is using `4.6.0`
and the following code is used:

```
const toName = 'some string;
const transaction = apm.startTransaction(toName, 'route-change');
const span = transaction.startSpan(toName, 'route-change');
```

then it works as expected

However `4.7.0` introduced breaking changes. The above code now produces the following error:

```
TypeError: Cannot read property 'startSpan' of undefined
```

Did the api change?

**Comment by jahtalab** [comment]
Hi @chriswoodley , 

Thanks for reaching out.

This might be the result of [this change](https://github.com/elastic/apm-agent-rum-js/pull/569) where we fixed a bug related to setting `active` config option to false. Would you please confirm whether you have set the `active:false` in your apm config options?

Furthermore, `startTransaction` API is not guaranteed to return a transaction since depending on the configuration it might not be able to do so, therefore it is a good idea to check the output of this method before using it. For more information please see our [docs](https://www.elastic.co/guide/en/apm/agent/rum-js/current/agent-api.html#apm-start-transaction).

**Comment by chriswoodley** [comment]
@jahtalab thanks for the quick response. For development we are setting that property value to `false` as shown below:

```
const apm = initApm({
  serviceName: process.env.VUE_APP_ELASTIC_SERVICE_NAME,
  serverUrl: process.env.VUE_APP_ELASTIC_SERVER_URL,
  environment: process.env.NODE_ENV,
  active: process.env.NODE_ENV !== 'development',
});
```

**Comment by chriswoodley** [comment]
@jahtalab looks like we need to handle `startTransaction ` as you suggested. Thanks!

**Comment by jahtalab** [comment]
We also have plans to simplify this with [returning a noop transaction](https://github.com/elastic/apm-agent-rum-js/issues/249)
Closing this as duplicate.
