### ISSUE TITLE
Add Bundle details as a comment in PRs

### ISSUE THREAD

**Issue by kuisathaverat** [elastic/apm-agent-rum-js#667]
It is interesting to have the bundle detail on a comment in PRs, something like the https://github.com/preactjs/compressed-size-action do, we have implemented a GitHub check that reports the bundle test result, so it is a matter of grab the details and put it in a GitHub comment that we should reutilize. 

https://github.com/elastic/apm-agent-rum-js/blob/master/Jenkinsfile#L328-L346

**Comment by v1v** [comment]
We got this particular PR comment feature in place:

```
githubPrComment(commentFile: 'bundle.id', message: '<markdown format with the bundle details>')
```

I'll raise an issue in our library to support this case among some others.

**Comment by vigneshshanmugam** [comment]
@v1v Awesome stuff, looking forward to seeing this in action.

**Comment by v1v** [comment]
What do you think with something like the below comment?

https://github.com/elastic/apm-agent-rum-js/pull/826#issuecomment-649124576

**Comment by vigneshshanmugam** [comment]
@v1v Would be interested in the gzipped size of the individual asset and also a diff of the current vs master branch.

**Comment by v1v** [comment]
@vigneshshanmugam , what do you think the below comment?
- https://github.com/elastic/apm-agent-rum-js/pull/826#issuecomment-650255846

In order to generate those details I created a specific implementation in our shared library, the one we use for adding more features in the Jenkinsfile.

### How does it work?

The html bundlesize reports are transformed in json -> [here](https://apm-ci.elastic.co/job/apm-agent-rum/job/apm-agent-rum-mbp/job/PR-826/11/artifact/bundlesize.json)

#### What data is populated in the comment?
- statSize
- gzipSize


#### How to compare with the master branch or another branch?

If there is a similar `bundlesize.json` in the master branch or the branch where the PR will be merged into then it will be compared and will add some details to the above-mentioned JSON files, for instance:

![image](https://user-images.githubusercontent.com/2871786/85877217-b7062280-b7ce-11ea-8183-57f51c42d438.png)

__NOTE__: red when the size increased and green when the opposite.

The above image was generated with some mock data. 

Please let me know what you think

**Comment by vigneshshanmugam** [comment]
@v1v Beautiful 🎉 , Thanks a ton for doing it. Just an small change, Lets add the diff based on `gzipSize` and not raw bundle size as sometimes bundle might increase but would give reduced gzip size and our bundle size reports are already based on gzipped size so its good to keep it in sync. Other than that, It looks really good.
