### ISSUE TITLE
CI: add a check to PRs to enforce conventional commit message

### ISSUE THREAD

**Issue by jahtalab** [elastic/apm-agent-rum-js#674]
We should enforce the conventional commit messages (e.g. `feat(rum-core): new feature`) in the PRs

cc @elastic/observablt-robots

**Comment by v1v** [comment]
A few questions:
- A pre-validation before any tests are executed?
- Should fail-fast? Or should notify with a warning?

**Comment by vigneshshanmugam** [comment]
If we are doing this, then it should be done as part of the lint phase. Example - https://github.com/conventional-changelog/commitlint

**Comment by kuisathaverat** [comment]
the same we have for the Node.js agent, the thing that Victor ask is, if you want this lint stage at the beginning of the pipeline and if a failure on the linting should abort the build. On other pipelines, the linting stages are at the beginning and the build is aborted if it fails. The alternative is to mark the build as UNSTABLE (Yellow) instead of FAILED (red)

**Comment by jahtalab** [comment]
I think it's ok to fail early in the lint stage, in general the author of the PR is expected to fix the commit messages and push again which should trigger another test.

**Comment by vigneshshanmugam** [comment]
Got it, Yes The build should fail fast at lint stage and abort the pipeline.

**Comment by v1v** [comment]
PR: https://github.com/elastic/apm-agent-rum-js/pull/704
