### ISSUE TITLE
Proper way to handle apm in bundle and on page (Docs)

### ISSUE THREAD

**Issue by science695** [elastic/apm-agent-rum-js#830]
I've been looking at the issue of how do you handle apm rum included both in a global header for my site, and in webpack bundles for certain apps.

Use case:

> I have 3 single page apps that have apm in their bundles, but I also want apm running globally on my site to track performance of the static pages.
> 
> I tried loading it on the page, and having the bundle access it. But it seemed like the bundle wasn't being instrumented properly.
> 
> Now I have it in the bundle, and it exposing the variable to apm, but I still get errors saying window.elasticApm is undefined. (not sure if that's a race condition, or if I'm doing something terribly wrong)

I've seen several issues on avoiding multiple apm instances, double reporting, etc... #791, #799, ...

With those issues, and their fixes, is there anyplace in the docs that shows the best way(s) to setup apm instances with and without bundles and avoiding duplicate loading and/or reporting?

**Comment by vigneshshanmugam** [comment]
@science695 We don't have docs on whats best when handling the apm instances across multiple apps and bundlers. 

Since you are using webpack, It would be better to load the APM bundle in shared dependencies(In this way you eliminate the `@elastic/apm-rum` getting bundled multiple times in 3 apps) and your app code could import the apm dependencies and webpack would make sure that module is shared and will not add it to the bundle. Mode details here - https://webpack.js.org/guides/code-splitting/#prevent-duplication

 However you would need to access the apm by using `import apm from 'elastic/apm-rum' `  and accessing the `apm` instance and not via `window.elasticApm` as it would create race condition unless you are sure both scripts are executed in the order (which in most cases wont be). 

Let us know if you need any other information.

**Comment by jahtalab** [comment]
Closing this one, feel free to reopen if more information needed.
